# Generated by Django 5.0.2 on 2024-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(),
        ),
    ]
