# Generated by Django 5.0.2 on 2024-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0002_rename_data_reservations_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
