# Generated by Django 5.0.2 on 2024-03-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0003_alter_reservations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
