# Generated by Django 5.0.2 on 2024-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0004_alter_reservations_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(choices=[('1', '1pm'), ('2', '2pm'), ('3', '3pm'), ('4', '4pm'), ('5', '5pm')], max_length=50, null=True),
        ),
    ]
